name: Check for Sensitive Info

on: [push, pull_request]

jobs:
  check_sensitive_info:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: qinwuyuan-sync-bot
      GIT_COMMITTER_EMAIL: qinwuyuan-sync-bot@users.noreply.github.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Check for email
        id: check_email
        run: |
          FILES=$(git diff --name-only HEAD^ HEAD)
          FOUND=false
          for FILE in $FILES; do
            if grep -q '123456@gmail.com' "$FILE"; then
              echo "Sensitive info found in $FILE!"
              FOUND=true
            fi
          done
          if [ "$FOUND" = true ]; then
            echo "Sensitive info found, restoring to parent commit."
            git reset --hard HEAD^
            git add .
            git commit -m "Reverted commit due to sensitive information detected"
            git push origin HEAD --force
            exit 1
          else
            echo "No sensitive info found."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
