name: Format and Push JavaScript Files

on:
    #   schedule:
    #        - cron: "0 2 * * 2" # 每周二的 UTC 时间 2 点，即北京时间的早上 10 点
    workflow_dispatch: # 允许手动触发工作流

  
jobs:
  format-js:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository from bak branch
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: bak  # 指定检出 bak 分支
          token: ${{ secrets.MY_GITHUB_TOKEN }} 
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # 使用 GitHub 提供的自动令牌

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 可以根据需要调整

      # Step 3: Run the custom formatting script (1.js)
      - name: Run format script
        run: node 1.js

      # Step 4: Commit and push changes back to the bak branch (if any)
      - name: Commit and push changes
          # 在推送时使用 GitHub Token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-format JavaScript files" || echo "No changes to commit"
          # 使用 GITHUB_TOKEN 来进行身份验证和推送
          #git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin bak  # 指定推送到 bak 分支
        env:
            MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
